blank_issues_enabled: false
contact_links:
  - name: R Club Discord Community
    url: https://discord.gg/ZqFyhU6fM3
    about: Here you can ask live support and/or recruit developers (or other team members) for your projects.